[general]
import = ["~/.config/alacritty/themes/themes/tokyo_night_storm.toml"]

[font]
size = 12.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
key = "Left"
mods = "Command"
chars = "\u0001" # Ctrl-A (start of line)

[[keyboard.bindings]]
key = "Right"
mods = "Command"
chars = "\u0005" # Ctrl-E (end of line)

# for TMUX fast pane switching
[[keyboard.bindings]]
key = "Key0"
mods = "Alt"
chars = "\u001b0" # Alt-1 → ESC + 1

[[keyboard.bindings]]
key = "Key1"
mods = "Alt"
chars = "\u001b1" # Alt-1 → ESC + 1

[[keyboard.bindings]]
key = "Key2"
mods = "Alt"
chars = "\u001b2" # Alt-2 → ESC + 2

[[keyboard.bindings]]
key = "Key3"
mods = "Alt"
chars = "\u001b3" # Alt-3 → ESC + 3

[window]
dynamic_title = true
option_as_alt = "OnlyRight"

#[[keyboard.bindings]]
#key = "Return"
#mods = "Command"
#chars = "\u001b[25~" # \u001b is ESC, so this is ESC[25~ ; F13 key
#
#[[keyboard.bindings]]
#key = "Return"
#mods = "Control"
#chars = "\u001b[26~" # F14
